# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bucketlistitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucketlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bucketlistitem',
            name='bucketlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bucketlist.BucketList'),
        ),
    ]
